language: generic
sudo: false

branches:
  only:
    - master
    - /^\d+\.\d+.*$/

os:
  - linux

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - $HOME/miniconda/bin/conda install conda conda-build conda-verify anaconda-client --yes
  - source $HOME/miniconda/bin/activate
  # Needed for click-repl at the moment
  - conda config --append channels conda-forge
  - conda info -a

script:
  - conda build conda-recipe
