language: generic
sudo: false
branches:
  only:
  - master
  - "/^\\d+\\.\\d+.*$/"
os:
- linux
install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -p $HOME/miniconda
- source $HOME/miniconda/bin/activate
- conda config --append channels conda-forge
- conda install conda conda-build conda-verify anaconda-client --yes
- conda info -a
script:
- conda build conda-recipe
deploy:
- provider: script
  skip_cleanup: true
  on:
    branch: master
    tags: true
  script: anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin $HOME/miniconda/conda-bld/*/*.tar.bz2
    --force
- provider: script
  skip_cleanup: true
  on:
    branch: master
    tags: false
  script: anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin --label
    dev $HOME/miniconda/conda-bld/*/*.tar.bz2 --force
env:
  global:
  - secure: djU4Xa8VuvYeYBk/aukQFdNraHu8eC3so1yBEwcoDq0Xpfnjln90VnNg9yDvoRLR9MOJTSnlqozkpJ+HZ5JBTYuH0L1whkeeH3aSgWyfdfGk6nClNf9I1NZb/lHvobeIv4sz8CDVCQacgIX+sYUbAOA15xx203D6VAsaBDWaJxzt9wvdV8dzwV54Xgitj9pxFap+cyiIlt0Dy9pYeurztJeiDpRxSfQw+4KLlCwLnZa0oP4u7AVX1sxdbZm0QdiYHbL6O14ZvIHRnNyH5KTFFbSSqVpmaTvkPcorstEReReLT8Dl+TRnvSbava4qsjrUEsTuobUqAevImG/rzKUmRXOtxkJeTPAlrswmvgZcv4OlbxJL8oZrA5ciFK5O3kgkTXI+ZfCWPdysVnFApBhxKy/Uf4JhNb8PcTWAxFNNcvyfidH4s2Z9EMfMCmJK29cnghcgjBuw0fvsO8B55MO68D38j28VDJVbvpFQifLXbOxD4ZpL5ONrh+68Y84B2PlTm1xsRcFOlrm0EDba93O0g8MdY76tmwQsjYWuhtrTKQH/7/fbX/NIw9y9ZTmOqhhbyA2tB6V+ZX611NGby0gRl4JAgbrcormVFIoyrxs6wkRryEcqXMRYGImMQJcUXPGtKVqhv2b0DcY8BFcB4THGYQtNNPJWLvfglWsOxaxw/9U=
  - secure: MldxOigI7IePjcAgXqp0tfTFQh3W20lHLZVtXYKWEIhvq52S17uFC20/J2UngRwIH49GqWTVPuBWbCYUB0cHW0x+oZIvdJWwDp++0d+3M+vd8ReV7FkxJPfiH4uFcicdncuvmH3IlOI7V0HQXEvEWV1TzXRkw16ZQHacgNEDPj+Um/b1uWcEeLtW6WordR0veNFGOnYcewXLxyzFAF9EXMOZCd62Aa8FW5S2yXFVWws/zRJcC5ZK0352BAFBjDOTD4RR7XGABdyr/Iajaxq2efYzBHt9RaAQZhhp+vgqITUvPtolTQO8W3gXasG3z2aUNOcOzlUzuiATtS4FI0JsxGzrXf+jhydjXfV02pMbvH5xpPEjcNptzyivxCaCUVgpnA1Mh1F7iBt848awu3NtMp1JcBAFhmRT2JkB0tkNmmyVFk3UhgbziB4SQ8Dq1DpDDzZ/LdD3R12aTENwKzpqINhuJBkOxXgB2NNaJwhA00/R4ses3nJBLIEt7DdiNC6M653OYNMe3Ixy/RHtLXCyE6GBLO9wnFwoNfGvA9UQduGcLdXlmOdYGRLu45M/jDNJumPOPVdSBNueNsT+19KlAHl5mGnmoyQcJ4CAWoOXlGlKhh0bYR5SoziKvsrjtUKRVJLFXvQNo6u4aoqRxQNe4iOrrI4jiC/nFQFBTdMgJmc=
