{% set data = load_setup_py_data() %}

package:
  name: ae5_tools
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - setuptools
  run:
    - python>=3.6
    - requests
    - pandas
    - click
    - click-repl
    - lxml

about:
  home: https://github.com/Anaconda-Platform/ae5-tools
  summary: 'Command-line manipulation of Anaconda Enterprise.'
