{% set data = load_setup_py_data() %}

package:
  name: ae5-tools
  version: {{ data.get('version').lstrip('v') }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - ae5 = ae5_tools.cli.main:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python>=3.6
    - requests
    - pandas
    - click>=7
    - click-repl
    - lxml

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test -xv tests
    - ae5 --help
    - ae5 --help-login
    - ae5 --help-format
    - ae5 project --help
    - ae5 session --help
    - ae5 deployment --help

about:
  home: https://github.com/Anaconda-Platform/ae5-tools
  summary: 'Command-line manipulation of Anaconda Enterprise 5.'
